### PR TITLE
Update Andy to v0.27

### PR DESCRIPTION
**Pull request by Arraying**
This pull request will contain all the changes necessary to make these assignments work on the new version of Andy.

### CODE REVIEW

**Comment by martinmladenov** [comment]
I added the CI script from #9 to test the assignments

**Comment by martinmladenov** [comment]
@Arraying The plugin version needs to be updated from 0.2 to 0.3 too.

**Comment by Arraying** [comment]
Are we ready to merge @martinmladenov?

**Review by martinmladenov — APPROVED** [review]
Looks good!

**Comment by martinmladenov** [comment]
Maybe we should merge #9 first, though

**Pull request merged**
